import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from './Navbar';
import Provider from './auth/Provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-theme='winter' lang='en'>
      <Provider>
        <body className={inter.className}>
          <Navbar />
          <main className='p-5'>{children}</main>
        </body>
      </Provider>
    </html>
  );
}
